-- Generated by nwg-displays on 2026-05-27 at 09:43:28. Do not edit manually.

hl.monitor({
    output = "desc:Lenovo Group Limited 0x40A9",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10
})
