-- Generated by nwg-displays on 2026-05-27 at 09:35:24. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "eDP-1"
})
