hl.curve("wind",   { type = "bezier", points = { {0, 1.05},   {0.41, 1} } })
hl.curve("winIn",  { type = "bezier", points = { {0.31, 0.53}, {0.26, 1} } })
hl.curve("winOut", { type = "bezier", points = { {0.3, -0.3},  {0, 1}    } })
hl.curve("liner",  { type = "bezier", points = { {1, 1},       {1, 1}    } })

hl.animation({ leaf = "windows",      enabled = true, speed = 4,  bezier = "wind",  style = "slide" })
hl.animation({ leaf = "windowsIn",    enabled = true, speed = 4,  bezier = "winIn", style = "popin 0%" })
hl.animation({ leaf = "windowsOut",   enabled = true, speed = 4,  bezier = "winOut", style = "popin 0%" })
hl.animation({ leaf = "windowsMove",  enabled = true, speed = 4,  bezier = "wind",  style = "slide" })
hl.animation({ leaf = "border",       enabled = true, speed = 1,  bezier = "liner" })
hl.animation({ leaf = "borderangle",  enabled = true, speed = 1,  bezier = "liner", style = "once" })
hl.animation({ leaf = "fade",         enabled = true, speed = 6,  bezier = "default" })
hl.animation({ leaf = "workspaces",   enabled = true, speed = 5,  bezier = "wind" })
hl.animation({ leaf = "layersIn",     enabled = true, speed = 5,  bezier = "wind",  style = "slide 0%" })
hl.animation({ leaf = "layersOut",    enabled = true, speed = 2,  bezier = "liner", style = "slide 100%" })
